name: Compiles binary, upload to release
on:
  push:
    branches: main
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -C target-feature=+crt-static
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --target x86_64-unknown-linux-gnu --release --verbose
      - name: Move
        run: mv ./target/x86_64-unknown-linux-gnu/release/prochrome .
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          title: "Current binary"
          files: prochrome
